

# python mcts_main_parallel_new.py --test_case "test-cases/hard/test01.txt" --time_limit 5 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test02.txt" --time_limit 5 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test03.txt" --time_limit 5 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test04.txt" --time_limit 5 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test05.txt" --time_limit 5 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test06.txt" --time_limit 5 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test07.txt" --time_limit 5 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test08.txt" --time_limit 5 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test09.txt" --time_limit 5 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test10.txt" --time_limit 5 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test11.txt" --time_limit 5 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test12.txt" --time_limit 5 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test13.txt" --time_limit 5 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test14.txt" --time_limit 5 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test10.txt" --time_limit 5 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test16.txt" --time_limit 5 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test17.txt" --time_limit 5 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test18.txt" --time_limit 5 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test19.txt" --time_limit 5 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test20.txt" --time_limit 5 --num_envs 500 --headless;


# python mcts_main_parallel_new.py --test_case "test-cases/hard/test01.txt" --time_limit 15 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test02.txt" --time_limit 15 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test03.txt" --time_limit 15 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test04.txt" --time_limit 15 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test05.txt" --time_limit 15 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test06.txt" --time_limit 15 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test07.txt" --time_limit 15 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test08.txt" --time_limit 15 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test09.txt" --time_limit 15 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test10.txt" --time_limit 15 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test11.txt" --time_limit 15 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test12.txt" --time_limit 15 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test13.txt" --time_limit 15 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test14.txt" --time_limit 15 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test15.txt" --time_limit 15 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test16.txt" --time_limit 15 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test17.txt" --time_limit 15 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test18.txt" --time_limit 15 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test19.txt" --time_limit 15 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test20.txt" --time_limit 15 --num_envs 500 --headless;

python mcts_main_parallel_new.py --test_case "test-cases/hard/test01.txt" --time_limit 30 --num_envs 500 --headless;
python mcts_main_parallel_new.py --test_case "test-cases/hard/test02.txt" --time_limit 30 --num_envs 500 --headless;
python mcts_main_parallel_new.py --test_case "test-cases/hard/test03.txt" --time_limit 30 --num_envs 500 --headless;
python mcts_main_parallel_new.py --test_case "test-cases/hard/test04.txt" --time_limit 30 --num_envs 500 --headless;
python mcts_main_parallel_new.py --test_case "test-cases/hard/test05.txt" --time_limit 30 --num_envs 500 --headless;
python mcts_main_parallel_new.py --test_case "test-cases/hard/test06.txt" --time_limit 30 --num_envs 500 --headless;
python mcts_main_parallel_new.py --test_case "test-cases/hard/test07.txt" --time_limit 30 --num_envs 500 --headless;
python mcts_main_parallel_new.py --test_case "test-cases/hard/test08.txt" --time_limit 30 --num_envs 500 --headless;
python mcts_main_parallel_new.py --test_case "test-cases/hard/test09.txt" --time_limit 30 --num_envs 500 --headless;
python mcts_main_parallel_new.py --test_case "test-cases/hard/test10.txt" --time_limit 30 --num_envs 500 --headless;
python mcts_main_parallel_new.py --test_case "test-cases/hard/test11.txt" --time_limit 30 --num_envs 500 --headless;
python mcts_main_parallel_new.py --test_case "test-cases/hard/test12.txt" --time_limit 30 --num_envs 500 --headless;
python mcts_main_parallel_new.py --test_case "test-cases/hard/test13.txt" --time_limit 30 --num_envs 500 --headless;
python mcts_main_parallel_new.py --test_case "test-cases/hard/test14.txt" --time_limit 30 --num_envs 500 --headless;
python mcts_main_parallel_new.py --test_case "test-cases/hard/test15.txt" --time_limit 30 --num_envs 500 --headless;
python mcts_main_parallel_new.py --test_case "test-cases/hard/test16.txt" --time_limit 30 --num_envs 500 --headless;
python mcts_main_parallel_new.py --test_case "test-cases/hard/test17.txt" --time_limit 30 --num_envs 500 --headless;
python mcts_main_parallel_new.py --test_case "test-cases/hard/test18.txt" --time_limit 30 --num_envs 500 --headless;
python mcts_main_parallel_new.py --test_case "test-cases/hard/test19.txt" --time_limit 30 --num_envs 500 --headless;
python mcts_main_parallel_new.py --test_case "test-cases/hard/test20.txt" --time_limit 30 --num_envs 500 --headless;

# python mcts_main_parallel_new.py --test_case "test-cases/hard/test01.txt" --time_limit 60 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test02.txt" --time_limit 60 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test03.txt" --time_limit 60 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test04.txt" --time_limit 60 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test05.txt" --time_limit 60 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test06.txt" --time_limit 60 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test07.txt" --time_limit 60 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test08.txt" --time_limit 60 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test09.txt" --time_limit 60 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test10.txt" --time_limit 60 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test11.txt" --time_limit 60 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test12.txt" --time_limit 60 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test13.txt" --time_limit 60 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test14.txt" --time_limit 60 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test15.txt" --time_limit 60 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test16.txt" --time_limit 60 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test17.txt" --time_limit 60 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test18.txt" --time_limit 60 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test19.txt" --time_limit 60 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test20.txt" --time_limit 60 --num_envs 500 --headless;

# python mcts_main_parallel_new.py --test_case "test-cases/hard/test01.txt" --time_limit 120 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test02.txt" --time_limit 120 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test03.txt" --time_limit 120 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test04.txt" --time_limit 120 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test05.txt" --time_limit 120 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test06.txt" --time_limit 120 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test07.txt" --time_limit 120 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test08.txt" --time_limit 120 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test09.txt" --time_limit 120 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test10.txt" --time_limit 120 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test11.txt" --time_limit 120 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test12.txt" --time_limit 120 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test13.txt" --time_limit 120 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test14.txt" --time_limit 120 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test15.txt" --time_limit 120 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test16.txt" --time_limit 120 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test17.txt" --time_limit 120 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test18.txt" --time_limit 120 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test19.txt" --time_limit 120 --num_envs 500 --headless;
# python mcts_main_parallel_new.py --test_case "test-cases/hard/test20.txt" --time_limit 120 --num_envs 500 --headless;
